language: python
python:
  - "3.8"
install:
  - pip install --editable .
  - cd examples 
  - pip install -r requirements.txt
  - cd ..
  - sudo fallocate -l 16G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - free -h
script:
  - cd tests
  - python utils/download_models.py
  - pytest 
